//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zy_erp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Production_Plan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Production_Plan()
        {
            this.T_Production_Plan_Details = new HashSet<T_Production_Plan_Details>();
        }
    
        public int Production_Planid { get; set; }
        public string product_name { get; set; }
        public Nullable<int> Production_quantity { get; set; }
        public string head { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> state { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Production_Plan_Details> T_Production_Plan_Details { get; set; }
    }
}
