//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zy_erp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PurchaseOrders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_PurchaseOrders()
        {
            this.T_PurchaseOrders_Details = new HashSet<T_PurchaseOrders_Details>();
        }
    
        public int purchaseorderid { get; set; }
        public Nullable<int> supplierid { get; set; }
        public Nullable<decimal> purchaseorder_price { get; set; }
        public Nullable<int> purchaseorder_numberMax { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> state_ok { get; set; }
        public Nullable<int> output_ok { get; set; }
        public Nullable<decimal> random { get; set; }
        public Nullable<decimal> random2 { get; set; }
        public Nullable<decimal> random3 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_PurchaseOrders_Details> T_PurchaseOrders_Details { get; set; }
        public virtual T_Supplier T_Supplier { get; set; }
    }
}
