//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zy_erp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Raw_Material_output_Details
    {
        public int Raw_Material_output_Detailsid { get; set; }
        public Nullable<int> outputid { get; set; }
        public Nullable<int> rawmaterialid { get; set; }
        public Nullable<int> rawmaterial_inventory { get; set; }
    
        public virtual T_Raw_Material T_Raw_Material { get; set; }
        public virtual T_Raw_Material_output T_Raw_Material_output { get; set; }
    }
}
