//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zy_erp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Raw_Material_Inventory
    {
        public int Inventoryid { get; set; }
        public Nullable<int> rawmaterialtid { get; set; }
        public Nullable<int> purchcount { get; set; }
        public Nullable<int> salescount { get; set; }
        public Nullable<int> stockcount { get; set; }
    
        public virtual T_Raw_Material T_Raw_Material { get; set; }
    }
}
