//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zy_erp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Raw_Material_Type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Raw_Material_Type()
        {
            this.T_Supplier_Raw_Material_Type = new HashSet<T_Supplier_Raw_Material_Type>();
        }
    
        public int rawmaterialtypeid { get; set; }
        public string rawmaterialtype_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Supplier_Raw_Material_Type> T_Supplier_Raw_Material_Type { get; set; }
    }
}
