//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zy_erp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Raw_Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Raw_Material()
        {
            this.T_PurchaseOrders_Details = new HashSet<T_PurchaseOrders_Details>();
            this.T_Raw_Material_output = new HashSet<T_Raw_Material_output>();
        }
    
        public int rawmaterialtid { get; set; }
        public string rawmaterial_name { get; set; }
        public Nullable<int> rawmaterial_inventory { get; set; }
        public Nullable<decimal> rawmaterial_price { get; set; }
        public string rawmaterial_introduce { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_PurchaseOrders_Details> T_PurchaseOrders_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Raw_Material_output> T_Raw_Material_output { get; set; }
    }
}
