//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zy_erp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Supplier_Raw_Material_Type
    {
        public int Supplier_Raw_Material_Typeid { get; set; }
        public Nullable<int> rawmaterialtypeid { get; set; }
        public Nullable<int> supplierid { get; set; }
    
        public virtual T_Raw_Material_Type T_Raw_Material_Type { get; set; }
        public virtual T_Supplier T_Supplier { get; set; }
    }
}
